### PR TITLE
Enable GitHub actions

### PR DESCRIPTION
**Pull request by jpmartinspt**

### CODE REVIEW

**Comment by nottrobin** [comment]
One thing I'm interested in here - with CircleCI, we get the ability to provide a base Docker image that the CI commands will run within. I noticed here we have "runs-on" - is that the same? Can we provide any base we want, or is it only a restricted set of basic OSs?

The reason I'm asking is because it would be really nice to be able to provide simple parity between the local `./run test` or `dotrun test` commands and what's run in CI. At the moment the format of our CircleCI jobs is all over the place, but at least in theory the ability to provide a basic docker image should mean we could simply be running e.g. `yarn run test` in CircleCI without needing to configure any extra package installs.

Or maybe we can simply use dotrun directly? Something like:

``` yaml
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/dotrun@v1
    - name: Run test
      run: dotrun test
```

**Comment by jpmartinspt** [comment]
I think this might be the closest [https://help.github.com/en/articles/creating-a-docker-container-action](https://help.github.com/en/articles/creating-a-docker-container-action) thing they support.

**Comment by jpmartinspt** [comment]
But you get docker as part of the `ubuntu-18.04` virtual environment too.

**Comment by nottrobin** [comment]
Yeah it looks like you can use docker images, even down to the individual step level. This looks more powerful than CircleCI, AFAIK:

https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-a-docker-hub-action

**Pull request closed without merging**
